# Generated by Django 4.2.3 on 2023-07-17 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the user_s name', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Userpass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passwd', models.CharField(help_text='enter a password', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.username')),
                ('passwd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.userpass')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the event', max_length=100)),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('status', models.CharField(choices=[('e', 'ended'), ('w', 'will still happen'), ('c', 'canceled'), ('i', 'is happening')], default='w', help_text='status of an event', max_length=1)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.username')),
            ],
        ),
    ]
