# Generated by Django 4.2.3 on 2023-07-22 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='null', help_text='Enter the user_s name', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='passwd',
            field=models.CharField(default='null', help_text='enter a password', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Username',
        ),
        migrations.DeleteModel(
            name='Userpass',
        ),
    ]
