# Generated by Django 4.2.3 on 2023-07-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_event_user_alter_user_name_alter_user_passwd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.CharField(default='null', help_text='Enter the user_s name', max_length=50),
            preserve_default=False,
        ),
    ]
