# Generated by Django 4.2.3 on 2023-07-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_event_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='begin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateField(),
        ),
    ]
